# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
  security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  admin.category_post:
          class: AppBundle\Admin\CategoryPostAdmin
          arguments: [~, AppBundle\Entity\CategoryPost, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Category Post", label: Category Post, label_catalogue: "AppBundle" }

  admin.blog_post:
          class: AppBundle\Admin\BlogPostAdmin
          arguments: [~, AppBundle\Entity\BlogPost, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Blog Post", label: Blog post, on_top: true }
          #calls:
            #- [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
